image:
  name: foundationbricks/foundation_brick_test
  entrypoint: [""]

variables:
  GITLAB_BASE_URL: 'https://mugitlab.mu-sigma.com'
  WORKFLOW_URL: 'https://eoc.mu-sigma.com/alfresco/s/foundationBricksAPI?format=json'
  : '16_Foundation_Brick_EDA_Package'
  GIT_GROUP_NAME: 'eoc_foundation'
  GIT_PROJECT_NAME: '16_FoundationBrick_EDA_Package'
  SOURCE: 'FoundationBrick'

stages:
  - updateVersion

runUpdateVersion:
  stage: updateVersion
  script:
    - cd support
    - python3 UpdateBricksVersion.py
    - version=`cat Description.json | jq '.version' | sed 's/"//g'`
    - fullnameOrig=$EOC_FILE_NAME"_v"$version".zip"
    - echo $EOC_FILE_NAME
    - newTag="v"$version
    - echo "$fullNameOrig"
    - echo $fullNameOrig
    - echo "$newTag"
    - cd ..
    - rm -rf .gitlab-ci.yml .gitignore .git
    - zip -r $fullnameOrig ./* -x support/UpdateBricksVersion.py
    - ls -al
    - >-
      curl -v
      -X POST $WORKFLOW_URL
      -H "Authorization: $AUTH_HEADER"
      -H 'content-type: multipart/form-data'
      -F file=@$fullNameOrig
      -F filename=$EOC_FILE_NAME
      -F groupname=$GIT_GROUP_NAME
      -F projectname=$GIT_PROJECT_NAME
      -F versioncode=$newTag
      -F source=$SOURCE
