image:
  name: foundationbricks/foundation_brick_test
  entrypoint: [""]

variables:
  GITLAB_BASE_URL: 'https://mugitlab.mu-sigma.com'
  WORKFLOW_URL: 'https://eoc.mu-sigma.com/alfresco/s/foundationBricksAPI?format=json'
  EOC_FILE_NAME: '16_Foundation_Brick_EDA_Package'
  GIT_GROUP_NAME: 'eoc_foundation'
  GIT_PROJECT_NAME: '16_FoundationBrick_EDA_Package'
  SOURCE: 'FoundationBrick'

stages:
  - updateVersion
  - pushFiles

runUpdateVersion:
  stage: updateVersion
  script:
    - cd support
    - python3 UpdateBricksVersion.py
    
runPushFiles:
  stage: pushFiles
  script: 
    - cd support
    - version=`cat Description.json | jq '.version' | sed 's/"//g'`
    - filename=`cat Description.json | jq '.filename' | sed 's/"//g'`
    - fullnameOrig=$filename"_v"$version".zip"
    - echo $fullNameOrig