---
title: "Exploratory Data Analysis"
author: 
 - name: Neeratyoy Mallik
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    

---


## Introduction




## Sourcing Utils File

```{r}
source('Poc.R')
source('EDAUtils.R')
```


## Creating an EDA object

```{r creating object, warning=F}

obj <- read_input(filePath = 'hotel_new.csv') 

print(obj@registry)
print(obj@recipe)

obj <- obj %>>% outlierPlot(method = "iqr",columnName = "Occupancy",cutoffValue = 0.01,priColor = "blue",optionalPlots = 0) %>>% univarCatDistPlots(uniCol = "building_type",priColor = "blue",optionalPlots = 0) 
print(obj@recipe)


obj1 <- obj %>>% generateOutput()


obj1[[2]]

```


## Register a new function

```{r register function, warning=F}

bivarPlots <- function(object,
                      select_var_name_1,
                      select_var_name_2,
                      priColor = "blue",secColor='black')
{
  x=object[, select_var_name_1]
  y=object[, select_var_name_2]
  bivarPlot <- ggplot2::ggplot(object, ggplot2::aes(x,y))+
    ggplot2::geom_point(color=priColor,alpha=0.7) +
    ggplot2::geom_smooth(method = lm,color=secColor)+
    ggplot2::xlab(select_var_name_1) +
    ggplot2::ylab(select_var_name_2) + ggplot2::theme_bw() +
    ggplot2::ggtitle(paste('Bivariate plot for',select_var_name_1,'and',select_var_name_2,sep=' '))+
    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10),axis.text = ggplot2::element_text(size=10),
                   axis.title=ggplot2::element_text(size=10))


  return(bivarPlot)

}


obj <- obj %>>% registerFunction('bivarPlots',"Bivariate Plots")

print(obj@registry)

obj <- obj %>>% bivarPlots('Occupancy','max_rooms_capacity',priColor = "blue","black")

print(obj@recipe)

obj1 <- obj %>>% generateOutput()


obj1[[3]]

```


## Generate Report

```{r generate report and tabs, warning=F,  eval=FALSE}

obj %>>% generateReport()

obj <- obj %>>% bivarPlots('Occupancy','PercentTransientNights',priColor = "blue","black")

obj %>>% generateReport()

```


## Save and Load

```{r load save , warning=F}
saveRecipe(obj,'obj.RDS')

obj2 <- loadRecipe('obj.RDS',filePath = 'hotel_new.csv') 

print(obj2@registry)
print(obj2@recipe)


```
