---
title: "Analysis Pipeline Results"

subtitle: '`r format(Sys.Date(), "%B %d, %Y")`'

output: html_document
  
params:
  obj: r! analysisPipelines::AnalysisPipeline() 
---

## Pipeline Visualization

```{r echo=FALSE, warning=FALSE, comment=FALSE, message=FALSE, results='asis', fig.width = 12, out.width = '100%'}
obj <- params$obj
input <- obj@input
pipelineDetails <-obj@pipeline
output <- obj@output


analysisPipelines::visualizePipeline(obj)
```


## Quick Peek
```{r quick peek,echo=FALSE,warning=FALSE,results='asis', fig.width = 12, out.width = '100%'}
DT::datatable(head(input),options = list(scrollX = T, scrollY = T))
```


```{r, echo =FALSE,warnings=FALSE,results='asis'}

# rowNo <- 1
outputDiagram <- ""

storedOps <- pipelineDetails %>>% dplyr::filter(storeOutput == T)

for(i in storedOps$id){
          opTable <- storedOps %>>% dplyr::filter(id == i)
          obj%>>% getOutputById(i) -> op
          knit_expanded <- paste0(
            "\n```{r chunk",i,",results='asis', fig.width = 12, out.width = '100%', echo=FALSE}
            \n\n
            cat('## ",opTable$heading," \n')
            \n\n
            op
            \n```
            \n\n"
        )
        outputDiagram <- paste0(outputDiagram, knit_expanded)
}

# while(1) {
# 
#     if(pipelineDetails[['operation']][[rowNo]] != pipelineDetails[['operation']][[rowNo+1]]){
# 
#         rowNo <- rowNo + 1
# 
#     }
    # else
    # # {
    #   outputDiagram <- paste0(outputDiagram, "\n`r {\"## ",pipelineDetails[['heading']][rowNo]," {.tabset}\"}`\n\n")
    #   tabNo=1
    #   while (1){
    #     knit_expanded <- paste0(
    #         "\n```{r chunk",rowNo,",results='asis', fig.width = 12, out.width = '100%', echo=FALSE}
    #         \n\n
    #         cat('### ",tabNo," \n')
    #         \n\n
    #         output[[",rowNo,"]]
    #         \n```
    #         \n\n"
    #     )
    #     outputDiagram <- paste0(outputDiagram, knit_expanded)
    #     rowNo <- rowNo + 1
    #     tabNo <- tabNo + 1
    #     if(pipelineDetails[['operation']][rowNo] != pipelineDetails[['operation']][rowNo-1])
    #       break
    #   }
    # }
    # 
    # if(rowNo > length(output))
    #   break    

# }


```


`r paste(knitr::knit(text = outputDiagram), collapse = '\n')`

