---
title: "Vignette for EDA Lite Brick"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r eruptions, echo=FALSE}



reactData <- reactiveValues(
  outString = '',
  colnames = '',
  output_report = ''
)

fileInput("inputFile", "Upload File")



observeEvent(input$inputFile,{
      reactData$outString <- ''
      reactData$outString <- paste0(reactData$outString,'eda(input=read.csv(\'/home/sanjay/Desktop/Test/hotel_new.csv\'))')
      reactData$colnames <- colnames(read.csv(input$inputFile$datapath))
})

selectInput("selectTask","Select Task",choices = c("Ignore Columns","Bivariate Plot","Univariate Cat Plot"))

uiOutput("taskInputs")

observeEvent(input$selectTask,
             if (input$selectTask == "Ignore Columns") {
               output$taskInputs <- renderUI(inputPanel(selectInput("var1","Select Column",choices = reactData$colnames)))
             }
             else if (input$selectTask == "Bivariate Plot") {
               output$taskInputs <- renderUI(inputPanel(selectInput("var1","Select Column 1",choices = reactData$colnames),
                                                     selectInput("var2","Select Column 2",choices = reactData$colnames)))
             }
             else {
              output$taskInputs <- renderUI(inputPanel(selectInput("var1","Select Column 1",choices = reactData$colnames)))
             })

tags$br()
             
actionButton("addPlot","Add")

observeEvent(input$addPlot,
             if (input$selectTask == "Ignore Columns") {
               reactData$outString <- paste0(reactData$outString,' %>>% ignoreColumns(\'',input$var1,'\')')
             }
             else if (input$selectTask == "Bivariate Plot") {
               reactData$outString <- paste0(reactData$outString,' %>>% bivarPlots(\'',input$var1,'\',\'',input$var2,'\')')
             }
             else {
               reactData$outString <- paste0(reactData$outString,' %>>% uniCatPlots(\'',input$var1,'\')')
             })



source("Poc.R")

tags$br()

tags$br()

actionButton("showTibble", "Show Tibble")

observeEvent(input$genReport, {
            reactData$output_report <- eval(parse(text = reactData$outString))
})

tags$br()

tags$br()

reactive(
  print(reactData$outString)
)
reactive(
  print(reactData$output_report)
)



```





